{
 "title": "Multi cluster monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance,prometheus) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Staging Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM overview",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(node_memory_MemTotal_bytes{prometheus=\"monitoring/staging\"}) by (prometheus), \"prometheus\", \"$1\", \"prometheus\", \".*/([^/]+)\")",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{prometheus=\"monitoring/staging\"}) by (prometheus)- sum(node_memory_MemAvailable_bytes) by (prometheus)",
     "legendFormat": "Total RAM used"
    }
   ]
  },
  {
   "title": "CPU overview",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",prometheus=\"monitoring/staging\"}[1m])))",
     "legendFormat": "Total RAM used"
    }
   ]
  },
  {
   "title": "Ram by nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(node_memory_MemTotal_bytes{prometheus=\"monitoring/staging\"}) by (instance), \"instance\", \"$1\", \"instance\", \"(.+):.+\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU usage by nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (instance) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",prometheus=\"monitoring/staging\"}[1m])),\"instance\", \"$1\", \"instance\", \"(.+):.+\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Production Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RAM overview",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(node_memory_MemTotal_bytes{prometheus=\"monitoring/production\"}) by (prometheus), \"prometheus\", \"$1\", \"prometheus\", \".*/([^/]+)\")",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{prometheus=\"monitoring/production\"}) by (prometheus)- sum(node_memory_MemAvailable_bytes) by (prometheus)",
     "legendFormat": "Total RAM used"
    }
   ]
  },
  {
   "title": "CPU overview",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",prometheus=\"monitoring/production\"}[1m])))",
     "legendFormat": "Total RAM used"
    }
   ]
  },
  {
   "title": "Ram by nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(node_memory_MemTotal_bytes{prometheus=\"monitoring/production\"}) by (instance), \"instance\", \"$1\", \"instance\", \"(.+):.+\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU usage by nodes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (instance) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",prometheus=\"monitoring/production\"}[1m])),\"instance\", \"$1\", \"instance\", \"(.+):.+\")",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}