apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: beta-Prom
  region: ap-south-1
  version: "1.29"


nodeGroups:
  - name: beta-Prom-node
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: false
