apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: staging
  namespace: monitoring
spec:
  image: quay.io/prometheus/prometheus:v2.49.1
  version: v2.49.1
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: devops-by-example

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 2Gi
  replicas: 1
  logLevel: info
  logFormat: logfmt
  retention: 6h
  scrapeInterval: 15s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: false
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: 'nfs-client'
        resources:
          requests:
            storage: 10Gi
  remoteWrite:
  - url: http://a359768d9cbfc4e77b099d89a5765d8f-1339349484.ap-south-1.elb.amazonaws.com:10908/api/v1/receive
    queueConfig:
      maxSamplesPerSend: 1000
      maxShards: 200
      capacity: 2500
